### ISSUE TITLE
Long starting times

### ISSUE THREAD

**Issue by spfaul** [cryptoAlgorithm/terminal-whatsapp#3]
Takes around roughly 20 secs to launch the UI after running `npm run start`. Mainly caused by the following imports of heavy libraries in `index.js`: 
```
const { WAConnection, MessageType} = require('@adiwajshing/baileys');
const { format } = require('date-fns');
const blessed = require('blessed');
const fs = require('fs');
const qrCode = require('qrcode-terminal');
const { parsePhoneNumber } = require('libphonenumber-js');
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
require('colors');
```

It's a major inconvenience and removes some of the project's appeal. Not sure if there's anything we can do about it on our end though...

**Comment by cryptoAlgorithm** [comment]
I don't know if its the issue with
* npm
* Your hardware
* Windows
but with Yarn and macOS Big Sur, even on old hardware startup times are 1-2 sec for the loading UI to appear.

Here's a screenrecord for reference:
<video autoplay controls src="https://user-images.githubusercontent.com/64193267/132977547-fc2d0f97-ecda-44cd-9497-dabde6759459.mov"/>

Ran first thru yarn, then by running `node index.js` directly. As you can see, excluding time in yarn, startup takes less than 2 seconds.

**Comment by spfaul** [comment]
yarn and running `node index.js` have the same result, so that takes npm out of the picture. I also doubt its my hardware as it starts up in under 2s on window's `cmd.exe`. Seems to just be a problem with WSL (or at least my WSL Kali install).

Node Version:  v14.12.0

**Comment by spfaul** [comment]
its probably the old node version that's causing this

**Comment by spfaul** [comment]
Update: updated npm to `v7.21.1` and node to `v16.9.1` - still same result. 

This problem is specific to WSL installs. Will use SSH as a temporary workaround for testing.

**Comment by cryptoAlgorithm** [comment]
Ok, may I inquire why you don't test it on the default cmd.exe instead?

**Comment by spfaul** [comment]
Would prefer to have the mouse functionality when testing .
